# permissions for end users to edit dhcpsubnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dhcpsubnet-editor-role
rules:
- apiGroups:
  - dhcp.bmcgo.dev
  resources:
  - dhcpsubnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dhcp.bmcgo.dev
  resources:
  - dhcpsubnets/status
  verbs:
  - get
