# permissions for end users to view dhcpleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dhcpleases-viewer-role
rules:
- apiGroups:
  - dhcp.bmcgo.dev
  resources:
  - dhcpleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.bmcgo.dev
  resources:
  - dhcpleases/status
  verbs:
  - get
